server:
  port: ${PORT:8080}

spring:
  application:
    name: countryService
  boot:
    admin:
      client:
        enabled: true
        url: http://microservice-monitoring:8080
        instance:
          service-url: http://microservice-microservice-country:8080

  liquibase:
    enabled: ${LIQ_ENABLE:false}
    drop-first: ${LIQ_DROP_FIRST:false}
    default-schema: country
    change-log: classpath:database-microservice-country-changelog.xml

  datasource:
    url: jdbc:${DATABASE_URL:postgresql://84.201.189.234:5432/postgres}
    username: ${USER_DB:postgres}
    password: ${PASS_DB:postgres}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: ${SCHEMA_DB:country}
    open-in-view: false
